export const DATA = [
    {
        bandImage: "image",
        bandName: "Band A",
        genres: ["Rock", "Pop"],
        bandSize: ["Pianiste", "Chanteur"],
        neededMusicians: ["Batteur", "Bassiste"],
        bandLevel: "Amateur",
        avgAge: 25,
        location: "Ile-de-France (Paris)",
    },
    {
        bandImage: "image",
        bandName: "Band B",
        genres: ["Rock", "Pop"],
        bandSize: ["Pianiste", "Chanteur"],
        neededMusicians: ["Batteur", "Bassiste"],
        bandLevel: "Amateur",
        avgAge: 25,
        location: "Ile-de-France (Paris)",
    },
    {
        bandImage: "image",
        bandName: "Band C",
        genres: ["Rock", "Pop"],
        bandSize: ["Pianiste", "Chanteur"],
        neededMusicians: ["Batteur", "Bassiste"],
        bandLevel: "Amateur",
        avgAge: 25,
        location: "Ile-de-France (Paris)",
    },
    {
        bandImage: "image",
        bandName: "Band D",
        genres: ["Rock", "Pop"],
        bandSize: ["Pianiste", "Chanteur"],
        neededMusicians: ["Batteur", "Bassiste"],
        bandLevel: "Amateur",
        avgAge: 25,
        location: "Ile-de-France (Paris)",
    },
    {
        bandImage: "image",
        bandName: "Band E",
        genres: ["Rock", "Pop"],
        bandSize: ["Pianiste", "Chanteur"],
        neededMusicians: ["Batteur", "Bassiste"],
        bandLevel: "Amateur",
        avgAge: 25,
        location: "Ile-de-France (Paris)",
    },
    {
        bandImage: "image",
        bandName: "Band F",
        genres: ["Rock", "Pop"],
        bandSize: ["Pianiste", "Chanteur"],
        neededMusicians: ["Batteur", "Bassiste"],
        bandLevel: "Amateur",
        avgAge: 25,
        location: "Ile-de-France (Paris)",
    },
    {
        bandImage: "image",
        bandName: "Band G",
        genres: ["Rock", "Pop"],
        bandSize: ["Pianiste", "Chanteur"],
        neededMusicians: ["Batteur", "Bassiste"],
        bandLevel: "Amateur",
        avgAge: 25,
        location: "Ile-de-France (Paris)",
    },
    {
        bandImage: "image",
        bandName: "Band H",
        genres: ["Rock", "Pop"],
        bandSize: ["Pianiste", "Chanteur"],
        neededMusicians: ["Batteur", "Bassiste"],
        bandLevel: "Amateur",
        avgAge: 25,
        location: "Ile-de-France (Paris)",
    },
    {
        bandImage: "image",
        bandName: "Band I",
        genres: ["Rock", "Pop"],
        bandSize: ["Pianiste", "Chanteur"],
        neededMusicians: ["Batteur", "Bassiste"],
        bandLevel: "Amateur",
        avgAge: 25,
        location: "Ile-de-France (Paris)",
    },
    {
        bandImage: "image",
        bandName: "Band J",
        genres: ["Rock", "Pop"],
        bandSize: ["Pianiste", "Chanteur"],
        neededMusicians: ["Batteur", "Bassiste"],
        bandLevel: "Amateur",
        avgAge: 25,
        location: "Ile-de-France (Paris)",
    },
    {
        bandImage: "image",
        bandName: "Band K",
        genres: ["Rock", "Pop"],
        bandSize: ["Pianiste", "Chanteur"],
        neededMusicians: ["Batteur", "Bassiste"],
        bandLevel: "Amateur",
        avgAge: 25,
        location: "Ile-de-France (Paris)",
    },
    {
        bandImage: "image",
        bandName: "Band L",
        genres: ["Rock", "Pop"],
        bandSize: ["Pianiste", "Chanteur"],
        neededMusicians: ["Batteur", "Bassiste"],
        bandLevel: "Amateur",
        avgAge: 25,
        location: "Ile-de-France (Paris)",
    },
    {
        bandImage: "image",
        bandName: "Band M",
        genres: ["Rock", "Pop"],
        bandSize: ["Pianiste", "Chanteur"],
        neededMusicians: ["Batteur", "Bassiste"],
        bandLevel: "Amateur",
        avgAge: 25,
        location: "Ile-de-France (Paris)",
    },
    {
        bandImage: "image",
        bandName: "Band N",
        genres: ["Rock", "Pop"],
        bandSize: ["Pianiste", "Chanteur"],
        neededMusicians: ["Batteur", "Bassiste"],
        bandLevel: "Amateur",
        avgAge: 25,
        location: "Ile-de-France (Paris)",
    },
]