export const DATA = [
  {
    bandImage: "image",
    bandName: "Band A",
    genres: ["Indé"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band B",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band C",
    genres: ["Jazz"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band D",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band E",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band F",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band G",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band H",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band I",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band J",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band K",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band L",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band M",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band N",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band O",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band P",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band Q",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band R",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band S",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band T",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band U",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band V",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band W",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band X",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band Y",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band Z",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band 1",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band 2",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band 3",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
  {
    bandImage: "image",
    bandName: "Band 4",
    genres: ["Rock", "Pop"],
    bandSize: 3,
    neededMusicians: ["Batteur", "Bassiste"],
    bandLevel: "Amateur",
    avgAge: 25,
    location: "Paris (75)",
  },
];
